# Generated by Django 5.2 on 2025-04-21 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_favorito'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='aprobado',
            field=models.BooleanField(default=False),
        ),
    ]
