# Generated by Django 5.2 on 2025-05-04 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_post_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagen',
            field=models.ImageField(default=1, upload_to='posts/imagenes_subidas/'),
            preserve_default=False,
        ),
    ]
